version: "3.7"

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - bridge

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=influxdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=pass
    volumes:
      - ./data:/var/lib/influxdb
    networks:
      - bridge
  
  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    networks:
      - bridge
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ./broker:/var/lib/kafka
    healthcheck:
      test: kafka-topics.sh --bootstrap-server 127.0.0.1:9092 -list || exit1
      interval: 2s
      timeout: 25s
      retries: 15
  
  albert-heat-pump:
    container_name: albert-heat-pump
    build: ./local/Albert/sensors/heat_pump
    command: python3 ./heat_pump.py
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=public
      - MQTT_PASSWORD=public
    networks:
      - bridge
    depends_on:
      - mosquitto
      - kafka

  albert-gateway:
    container_name: albert-gateway
    build: ./local/Albert/gateway
    command: python3 ./gateway.py
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=public
      - MQTT_PASSWORD=public
    networks:
      - bridge
    depends_on:
      mosquitto:
        condition: service_started
      kafka:
        condition: service_healthy

networks:
  bridge:
    driver: bridge
